#!/usr/bin/env python3
"""Emit TypeScript page registry and Expo Router stub screens from product_ui_ssot.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / "ui"
JSON_PATH = ROOT / "product_ui_ssot.json"
OUT_REGISTRY = UI / "src" / "ssot" / "generated" / "pageRegistry.ts"
APP = UI / "src" / "app"
TABS = frozenset(
    {
        "landing_page",
        "requests_posts_hub",
        "post_type_selector",
        "notifications_list",
        "account_profile",
    }
)

# Hand-maintained route files (not overwritten by stub generator)
HAND_AUTHORED = frozenset(
    {
        "landing_page",
        "map_view",
        "job_description",
        "worker_description",
        "signup_gate",
        "login_form",
        "signup_form",
        "requests_posts_hub",
        "post_type_selector",
        "notifications_list",
        "account_profile",
    }
)

# SSOT modal / sheet surfaces — presentation: modal in root Stack
MODALS = frozenset(
    {
        "options_menu",
        "discovery_filter",
        "sort_by_modal",
        "post_actions_sheet",
        "unfollow_confirmation_modal",
        "decline_rating",
        "delete_post_confirmation",
        "membership_cancel_confirm",
        "report_reason_selection",
        "report_message_input",
        "report_confirmation",
        "gallery_view",
    }
)


def pascal_route_component(page_id: str) -> str:
    return "".join(w.capitalize() for w in page_id.split("_")) + "Route"


def main() -> None:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    pages = data["pages"]
    page_ids = sorted(pages.keys(), key=str)

    OUT_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    APP.mkdir(parents=True, exist_ok=True)
    (APP / "(tabs)").mkdir(parents=True, exist_ok=True)

    lines = [
        "// AUTO-GENERATED by scripts/emit_ui_ssot_registry.py — do not edit by hand.",
        "",
        "export const PAGE_IDS = [",
    ]
    for pid in page_ids:
        lines.append(f'  "{pid}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type PageId = (typeof PAGE_IDS)[number];")
    lines.append("")
    lines.append("export const PAGE_TITLES: Record<PageId, string> = {")
    for pid in page_ids:
        title = pages[pid].get("name", pid).replace('"', '\\"')
        lines.append(f'  "{pid}": "{title}",')
    lines.append("};")
    lines.append("")
    modals_sorted = sorted(MODALS & frozenset(page_ids))
    lines.append("export const MODAL_PAGE_IDS: PageId[] = [")
    for m in modals_sorted:
        lines.append(f'  "{m}",')
    lines.append("];")
    lines.append("")
    OUT_REGISTRY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", OUT_REGISTRY)

    for pid in page_ids:
        if pid in HAND_AUTHORED:
            continue
        comp = pascal_route_component(pid)
        text = (
            'import { SsotRouteScreen } from "@/components/SsotRouteScreen";\n\n'
            f"export default function {comp}() {{\n"
            f'  return <SsotRouteScreen pageId="{pid}" />;\n'
            "}\n"
        )
        rel = (APP / "(tabs)" / f"{pid}.tsx") if pid in TABS else (APP / f"{pid}.tsx")
        rel.write_text(text, encoding="utf-8")
        print("Wrote", rel)

    print("Done. pages:", len(page_ids))


if __name__ == "__main__":
    main()
